name: codelingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/level.png
    - images/book.png
    - images/person.png
    - images/market.png
    - images/shield.png
    - images/level2.png
    - images/book2.png
    - images/market2.png
    - images/shield2.png
    - images/person2.png
    - images/spain.png
    - images/crown.png
    - images/offFire.png
    - images/gem.png
    - images/easter-egg.png
    - images/message.png
    - images/airplane.png
    - images/family.png
    - images/food.png
    - images/clothes.png
    - images/pencil.png
    - images/man.png


