// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qbK2ZQZiXlDUyxnFViiJ_HZM8Y87c7Y',
    appId: '1:431389313722:web:06b96bffd37146bb435083',
    messagingSenderId: '431389313722',
    projectId: 'code-lingo',
    authDomain: 'code-lingo.firebaseapp.com',
    storageBucket: 'code-lingo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzU1b4bEuHvsZsC05NLDJg2G_gAsLn2xY',
    appId: '1:431389313722:android:178d58da3bf9e8ff435083',
    messagingSenderId: '431389313722',
    projectId: 'code-lingo',
    storageBucket: 'code-lingo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT2EV71StemVJ70YrD6WsoYIVEMRkOHQ4',
    appId: '1:431389313722:ios:7ea508fa4d7426ed435083',
    messagingSenderId: '431389313722',
    projectId: 'code-lingo',
    storageBucket: 'code-lingo.appspot.com',
    iosBundleId: 'com.example.codelingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT2EV71StemVJ70YrD6WsoYIVEMRkOHQ4',
    appId: '1:431389313722:ios:7ea508fa4d7426ed435083',
    messagingSenderId: '431389313722',
    projectId: 'code-lingo',
    storageBucket: 'code-lingo.appspot.com',
    iosBundleId: 'com.example.codelingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1qbK2ZQZiXlDUyxnFViiJ_HZM8Y87c7Y',
    appId: '1:431389313722:web:3a9253bd377a48cb435083',
    messagingSenderId: '431389313722',
    projectId: 'code-lingo',
    authDomain: 'code-lingo.firebaseapp.com',
    storageBucket: 'code-lingo.appspot.com',
  );
}
